* custom-field-shortcode


[[https://img.shields.io/badge/version-VERSION-orange.svg][version]]

[[https://img.shields.io/badge/WordPress-Compatible-blue.svg][WordPress]]

Using shortcodes, place custom fields anywhere in your post content.

** Installation

Location: https://moria.whyayh.com/rel/released/software/own/plugin-custom-field-shortcode/

1. Use Add Plugins, upload Plugin custom-field-shortcode-VERSION.zip
2. Install and activate the plugin

** How do I use this plugin?

In your post's content, look for the custom fields and the bottom of
the post. You can short code with the custom field's name. That will
be replaced with the value of the custom field. For example:

#+begin_quote
  [custom_field field="your-custom-field-name"]
#+end_quote

Replace "your-custom-field-name" with one of the custom field name that
are available to the post. To see the custom fields that are available,
select the "..." menu option Preferences, section General, Advanced,
turn on "Custom fields"

HTML can be put around the [] text and multiple [] fields can be added.
For example:

#+begin_quote

  #+begin_html
    <p>
  #+end_html

  [custom~field field="usp-custom-subtitle"]

  #+begin_html
    </p>
  #+end_html

  #+begin_html
    <p>
  #+end_html

  by [custom_field field="usp-custom-author"]

  #+begin_html
    </p>
  #+end_html

  #+begin_html
    <p>
  #+end_html

  Link: [custom_field field="usp-custom-link"]> [custom_field
  field="usp-custom-link"]

  #+begin_html
    </p>
  #+end_html
#+end_quote

** How to uninstall the plugin?

Simply deactivate and delete the plugin.
